package SIGEV.BE;
// Generated 30/05/2015 06:26:47 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TCajaDetalle generated by hbm2java
 */
public class TCajaDetalle  implements java.io.Serializable {


     private int idcajadetalle;
     private TCaja TCaja;
     private String denominacion;
     private Integer idctipodetalle;
     private Double monto;
     private String estado;
     private String observacion;
     private Integer idusuariocreac;
     private Integer idusuariomodif;
     private Date fechacreac;
     private Date fechamodif;
     private Integer idrazonsocial;
     private Double subtotal;
     private Double egreso;
     private Double ingreso;

    public TCajaDetalle() {
    }

	
    public TCajaDetalle(int idcajadetalle) {
        this.idcajadetalle = idcajadetalle;
    }
    public TCajaDetalle(int idcajadetalle, TCaja TCaja, String denominacion, Integer idctipodetalle, Double monto, String estado, String observacion, Integer idusuariocreac, Integer idusuariomodif, Date fechacreac, Date fechamodif, Integer idrazonsocial, Double subtotal, Double egreso, Double ingreso) {
       this.idcajadetalle = idcajadetalle;
       this.TCaja = TCaja;
       this.denominacion = denominacion;
       this.idctipodetalle = idctipodetalle;
       this.monto = monto;
       this.estado = estado;
       this.observacion = observacion;
       this.idusuariocreac = idusuariocreac;
       this.idusuariomodif = idusuariomodif;
       this.fechacreac = fechacreac;
       this.fechamodif = fechamodif;
       this.idrazonsocial = idrazonsocial;
       this.subtotal = subtotal;
       this.egreso = egreso;
       this.ingreso = ingreso;
    }
   
    public int getIdcajadetalle() {
        return this.idcajadetalle;
    }
    
    public void setIdcajadetalle(int idcajadetalle) {
        this.idcajadetalle = idcajadetalle;
    }
    public TCaja getTCaja() {
        return this.TCaja;
    }
    
    public void setTCaja(TCaja TCaja) {
        this.TCaja = TCaja;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public Integer getIdctipodetalle() {
        return this.idctipodetalle;
    }
    
    public void setIdctipodetalle(Integer idctipodetalle) {
        this.idctipodetalle = idctipodetalle;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Integer getIdusuariocreac() {
        return this.idusuariocreac;
    }
    
    public void setIdusuariocreac(Integer idusuariocreac) {
        this.idusuariocreac = idusuariocreac;
    }
    public Integer getIdusuariomodif() {
        return this.idusuariomodif;
    }
    
    public void setIdusuariomodif(Integer idusuariomodif) {
        this.idusuariomodif = idusuariomodif;
    }
    public Date getFechacreac() {
        return this.fechacreac;
    }
    
    public void setFechacreac(Date fechacreac) {
        this.fechacreac = fechacreac;
    }
    public Date getFechamodif() {
        return this.fechamodif;
    }
    
    public void setFechamodif(Date fechamodif) {
        this.fechamodif = fechamodif;
    }
    public Integer getIdrazonsocial() {
        return this.idrazonsocial;
    }
    
    public void setIdrazonsocial(Integer idrazonsocial) {
        this.idrazonsocial = idrazonsocial;
    }
    public Double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Double subtotal) {
        this.subtotal = subtotal;
    }
    public Double getEgreso() {
        return this.egreso;
    }
    
    public void setEgreso(Double egreso) {
        this.egreso = egreso;
    }
    public Double getIngreso() {
        return this.ingreso;
    }
    
    public void setIngreso(Double ingreso) {
        this.ingreso = ingreso;
    }




}


