package SIGEV.BE;
// Generated 30/05/2015 06:26:47 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TCaja generated by hbm2java
 */
public class TCaja  implements java.io.Serializable {


     private int idcaja;
     private TBoveda TBoveda;
     private TUsuario TUsuario;
     private Double monto;
     private String estado;
     private String observacion;
     private Integer idusuariocreac;
     private Integer idusuariomodif;
     private Date fechacreac;
     private Date fechamodif;
     private Integer idrazonsocial;
     private Date fechaarqueo;
     private Set TCajaDetalles = new HashSet(0);

    public TCaja() {
    }

	
    public TCaja(int idcaja) {
        this.idcaja = idcaja;
    }
    public TCaja(int idcaja, TBoveda TBoveda, TUsuario TUsuario, Double monto, String estado, String observacion, Integer idusuariocreac, Integer idusuariomodif, Date fechacreac, Date fechamodif, Integer idrazonsocial, Date fechaarqueo, Set TCajaDetalles) {
       this.idcaja = idcaja;
       this.TBoveda = TBoveda;
       this.TUsuario = TUsuario;
       this.monto = monto;
       this.estado = estado;
       this.observacion = observacion;
       this.idusuariocreac = idusuariocreac;
       this.idusuariomodif = idusuariomodif;
       this.fechacreac = fechacreac;
       this.fechamodif = fechamodif;
       this.idrazonsocial = idrazonsocial;
       this.fechaarqueo = fechaarqueo;
       this.TCajaDetalles = TCajaDetalles;
    }
   
    public int getIdcaja() {
        return this.idcaja;
    }
    
    public void setIdcaja(int idcaja) {
        this.idcaja = idcaja;
    }
    public TBoveda getTBoveda() {
        return this.TBoveda;
    }
    
    public void setTBoveda(TBoveda TBoveda) {
        this.TBoveda = TBoveda;
    }
    public TUsuario getTUsuario() {
        return this.TUsuario;
    }
    
    public void setTUsuario(TUsuario TUsuario) {
        this.TUsuario = TUsuario;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Integer getIdusuariocreac() {
        return this.idusuariocreac;
    }
    
    public void setIdusuariocreac(Integer idusuariocreac) {
        this.idusuariocreac = idusuariocreac;
    }
    public Integer getIdusuariomodif() {
        return this.idusuariomodif;
    }
    
    public void setIdusuariomodif(Integer idusuariomodif) {
        this.idusuariomodif = idusuariomodif;
    }
    public Date getFechacreac() {
        return this.fechacreac;
    }
    
    public void setFechacreac(Date fechacreac) {
        this.fechacreac = fechacreac;
    }
    public Date getFechamodif() {
        return this.fechamodif;
    }
    
    public void setFechamodif(Date fechamodif) {
        this.fechamodif = fechamodif;
    }
    public Integer getIdrazonsocial() {
        return this.idrazonsocial;
    }
    
    public void setIdrazonsocial(Integer idrazonsocial) {
        this.idrazonsocial = idrazonsocial;
    }
    public Date getFechaarqueo() {
        return this.fechaarqueo;
    }
    
    public void setFechaarqueo(Date fechaarqueo) {
        this.fechaarqueo = fechaarqueo;
    }
    public Set getTCajaDetalles() {
        return this.TCajaDetalles;
    }
    
    public void setTCajaDetalles(Set TCajaDetalles) {
        this.TCajaDetalles = TCajaDetalles;
    }




}


