package SIGEV.BE;
// Generated 30/05/2015 06:26:47 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TCliente generated by hbm2java
 */
public class TCliente  implements java.io.Serializable {


     private int idcliente;
     private TPersona TPersona;
     private Integer idctipocliente;
     private Integer idcruta;
     private Integer idcfecuenciavisita;
     private Integer idctiponegocio;
     private String estado;
     private String observacion;
     private Integer idusuariocreac;
     private Integer idusuariomodif;
     private Date fechacreac;
     private Date fechamodif;
     private Set TVentas = new HashSet(0);

    public TCliente() {
    }

	
    public TCliente(int idcliente) {
        this.idcliente = idcliente;
    }
    public TCliente(int idcliente, TPersona TPersona, Integer idctipocliente, Integer idcruta, Integer idcfecuenciavisita, Integer idctiponegocio, String estado, String observacion, Integer idusuariocreac, Integer idusuariomodif, Date fechacreac, Date fechamodif, Set TVentas) {
       this.idcliente = idcliente;
       this.TPersona = TPersona;
       this.idctipocliente = idctipocliente;
       this.idcruta = idcruta;
       this.idcfecuenciavisita = idcfecuenciavisita;
       this.idctiponegocio = idctiponegocio;
       this.estado = estado;
       this.observacion = observacion;
       this.idusuariocreac = idusuariocreac;
       this.idusuariomodif = idusuariomodif;
       this.fechacreac = fechacreac;
       this.fechamodif = fechamodif;
       this.TVentas = TVentas;
    }
   
    public int getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }
    public TPersona getTPersona() {
        return this.TPersona;
    }
    
    public void setTPersona(TPersona TPersona) {
        this.TPersona = TPersona;
    }
    public Integer getIdctipocliente() {
        return this.idctipocliente;
    }
    
    public void setIdctipocliente(Integer idctipocliente) {
        this.idctipocliente = idctipocliente;
    }
    public Integer getIdcruta() {
        return this.idcruta;
    }
    
    public void setIdcruta(Integer idcruta) {
        this.idcruta = idcruta;
    }
    public Integer getIdcfecuenciavisita() {
        return this.idcfecuenciavisita;
    }
    
    public void setIdcfecuenciavisita(Integer idcfecuenciavisita) {
        this.idcfecuenciavisita = idcfecuenciavisita;
    }
    public Integer getIdctiponegocio() {
        return this.idctiponegocio;
    }
    
    public void setIdctiponegocio(Integer idctiponegocio) {
        this.idctiponegocio = idctiponegocio;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Integer getIdusuariocreac() {
        return this.idusuariocreac;
    }
    
    public void setIdusuariocreac(Integer idusuariocreac) {
        this.idusuariocreac = idusuariocreac;
    }
    public Integer getIdusuariomodif() {
        return this.idusuariomodif;
    }
    
    public void setIdusuariomodif(Integer idusuariomodif) {
        this.idusuariomodif = idusuariomodif;
    }
    public Date getFechacreac() {
        return this.fechacreac;
    }
    
    public void setFechacreac(Date fechacreac) {
        this.fechacreac = fechacreac;
    }
    public Date getFechamodif() {
        return this.fechamodif;
    }
    
    public void setFechamodif(Date fechamodif) {
        this.fechamodif = fechamodif;
    }
    public Set getTVentas() {
        return this.TVentas;
    }
    
    public void setTVentas(Set TVentas) {
        this.TVentas = TVentas;
    }




}


