package SIGEV.BE;
// Generated 30/05/2015 06:26:47 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TCompra generated by hbm2java
 */
public class TCompra  implements java.io.Serializable {


     private int idcompra;
     private TProveedor TProveedor;
     private Double montocompra;
     private String estado;
     private String observacion;
     private Integer idusuariocreac;
     private Integer idusuariomodif;
     private Date fechacreac;
     private Date fechamodif;
     private String comprovante;
     private Integer idrazonsocial;
     private Integer idcestadocompra;
     private Set TDetalleCompras = new HashSet(0);

    public TCompra() {
    }

	
    public TCompra(int idcompra) {
        this.idcompra = idcompra;
    }
    public TCompra(int idcompra, TProveedor TProveedor, Double montocompra, String estado, String observacion, Integer idusuariocreac, Integer idusuariomodif, Date fechacreac, Date fechamodif, String comprovante, Integer idrazonsocial, Integer idcestadocompra, Set TDetalleCompras) {
       this.idcompra = idcompra;
       this.TProveedor = TProveedor;
       this.montocompra = montocompra;
       this.estado = estado;
       this.observacion = observacion;
       this.idusuariocreac = idusuariocreac;
       this.idusuariomodif = idusuariomodif;
       this.fechacreac = fechacreac;
       this.fechamodif = fechamodif;
       this.comprovante = comprovante;
       this.idrazonsocial = idrazonsocial;
       this.idcestadocompra = idcestadocompra;
       this.TDetalleCompras = TDetalleCompras;
    }
   
    public int getIdcompra() {
        return this.idcompra;
    }
    
    public void setIdcompra(int idcompra) {
        this.idcompra = idcompra;
    }
    public TProveedor getTProveedor() {
        return this.TProveedor;
    }
    
    public void setTProveedor(TProveedor TProveedor) {
        this.TProveedor = TProveedor;
    }
    public Double getMontocompra() {
        return this.montocompra;
    }
    
    public void setMontocompra(Double montocompra) {
        this.montocompra = montocompra;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Integer getIdusuariocreac() {
        return this.idusuariocreac;
    }
    
    public void setIdusuariocreac(Integer idusuariocreac) {
        this.idusuariocreac = idusuariocreac;
    }
    public Integer getIdusuariomodif() {
        return this.idusuariomodif;
    }
    
    public void setIdusuariomodif(Integer idusuariomodif) {
        this.idusuariomodif = idusuariomodif;
    }
    public Date getFechacreac() {
        return this.fechacreac;
    }
    
    public void setFechacreac(Date fechacreac) {
        this.fechacreac = fechacreac;
    }
    public Date getFechamodif() {
        return this.fechamodif;
    }
    
    public void setFechamodif(Date fechamodif) {
        this.fechamodif = fechamodif;
    }
    public String getComprovante() {
        return this.comprovante;
    }
    
    public void setComprovante(String comprovante) {
        this.comprovante = comprovante;
    }
    public Integer getIdrazonsocial() {
        return this.idrazonsocial;
    }
    
    public void setIdrazonsocial(Integer idrazonsocial) {
        this.idrazonsocial = idrazonsocial;
    }
    public Integer getIdcestadocompra() {
        return this.idcestadocompra;
    }
    
    public void setIdcestadocompra(Integer idcestadocompra) {
        this.idcestadocompra = idcestadocompra;
    }
    public Set getTDetalleCompras() {
        return this.TDetalleCompras;
    }
    
    public void setTDetalleCompras(Set TDetalleCompras) {
        this.TDetalleCompras = TDetalleCompras;
    }




}


