package SIGEV.BE;
// Generated 30/05/2015 06:26:47 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TContenedor generated by hbm2java
 */
public class TContenedor  implements java.io.Serializable {


     private int idcontenedor;
     private Integer idtabla;
     private Integer iditem;
     private Integer idsuperior;
     private Integer orden;
     private String denominacion;
     private String abreviatura;
     private String estado;
     private String observacion;
     private Integer idusuariocreac;
     private Integer idusuariomodif;
     private Date fechacreac;
     private Date fechamodif;

    public TContenedor() {
    }

	
    public TContenedor(int idcontenedor) {
        this.idcontenedor = idcontenedor;
    }
    public TContenedor(int idcontenedor, Integer idtabla, Integer iditem, Integer idsuperior, Integer orden, String denominacion, String abreviatura, String estado, String observacion, Integer idusuariocreac, Integer idusuariomodif, Date fechacreac, Date fechamodif) {
       this.idcontenedor = idcontenedor;
       this.idtabla = idtabla;
       this.iditem = iditem;
       this.idsuperior = idsuperior;
       this.orden = orden;
       this.denominacion = denominacion;
       this.abreviatura = abreviatura;
       this.estado = estado;
       this.observacion = observacion;
       this.idusuariocreac = idusuariocreac;
       this.idusuariomodif = idusuariomodif;
       this.fechacreac = fechacreac;
       this.fechamodif = fechamodif;
    }
   
    public int getIdcontenedor() {
        return this.idcontenedor;
    }
    
    public void setIdcontenedor(int idcontenedor) {
        this.idcontenedor = idcontenedor;
    }
    public Integer getIdtabla() {
        return this.idtabla;
    }
    
    public void setIdtabla(Integer idtabla) {
        this.idtabla = idtabla;
    }
    public Integer getIditem() {
        return this.iditem;
    }
    
    public void setIditem(Integer iditem) {
        this.iditem = iditem;
    }
    public Integer getIdsuperior() {
        return this.idsuperior;
    }
    
    public void setIdsuperior(Integer idsuperior) {
        this.idsuperior = idsuperior;
    }
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Integer getIdusuariocreac() {
        return this.idusuariocreac;
    }
    
    public void setIdusuariocreac(Integer idusuariocreac) {
        this.idusuariocreac = idusuariocreac;
    }
    public Integer getIdusuariomodif() {
        return this.idusuariomodif;
    }
    
    public void setIdusuariomodif(Integer idusuariomodif) {
        this.idusuariomodif = idusuariomodif;
    }
    public Date getFechacreac() {
        return this.fechacreac;
    }
    
    public void setFechacreac(Date fechacreac) {
        this.fechacreac = fechacreac;
    }
    public Date getFechamodif() {
        return this.fechamodif;
    }
    
    public void setFechamodif(Date fechamodif) {
        this.fechamodif = fechamodif;
    }




}


