package SIGEV.BE;
// Generated 30/05/2015 06:26:47 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TDetalleCompra generated by hbm2java
 */
public class TDetalleCompra  implements java.io.Serializable {


     private int iddetallecompra;
     private TCompra TCompra;
     private TProducto TProducto;
     private Date fechavencimiento;
     private Integer cantidadcompra;
     private String estado;
     private String observacion;
     private Integer idusuariocreac;
     private Integer idusuariomodif;
     private Date fechacreac;
     private Date fechamodif;
     private Integer cantidaddaniado;
     private Integer idcobservacion;
     private Double subtotal;
     private Double preciocompraunid;

    public TDetalleCompra() {
    }

	
    public TDetalleCompra(int iddetallecompra) {
        this.iddetallecompra = iddetallecompra;
    }
    public TDetalleCompra(int iddetallecompra, TCompra TCompra, TProducto TProducto, Date fechavencimiento, Integer cantidadcompra, String estado, String observacion, Integer idusuariocreac, Integer idusuariomodif, Date fechacreac, Date fechamodif, Integer cantidaddaniado, Integer idcobservacion, Double subtotal, Double preciocompraunid) {
       this.iddetallecompra = iddetallecompra;
       this.TCompra = TCompra;
       this.TProducto = TProducto;
       this.fechavencimiento = fechavencimiento;
       this.cantidadcompra = cantidadcompra;
       this.estado = estado;
       this.observacion = observacion;
       this.idusuariocreac = idusuariocreac;
       this.idusuariomodif = idusuariomodif;
       this.fechacreac = fechacreac;
       this.fechamodif = fechamodif;
       this.cantidaddaniado = cantidaddaniado;
       this.idcobservacion = idcobservacion;
       this.subtotal = subtotal;
       this.preciocompraunid = preciocompraunid;
    }
   
    public int getIddetallecompra() {
        return this.iddetallecompra;
    }
    
    public void setIddetallecompra(int iddetallecompra) {
        this.iddetallecompra = iddetallecompra;
    }
    public TCompra getTCompra() {
        return this.TCompra;
    }
    
    public void setTCompra(TCompra TCompra) {
        this.TCompra = TCompra;
    }
    public TProducto getTProducto() {
        return this.TProducto;
    }
    
    public void setTProducto(TProducto TProducto) {
        this.TProducto = TProducto;
    }
    public Date getFechavencimiento() {
        return this.fechavencimiento;
    }
    
    public void setFechavencimiento(Date fechavencimiento) {
        this.fechavencimiento = fechavencimiento;
    }
    public Integer getCantidadcompra() {
        return this.cantidadcompra;
    }
    
    public void setCantidadcompra(Integer cantidadcompra) {
        this.cantidadcompra = cantidadcompra;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Integer getIdusuariocreac() {
        return this.idusuariocreac;
    }
    
    public void setIdusuariocreac(Integer idusuariocreac) {
        this.idusuariocreac = idusuariocreac;
    }
    public Integer getIdusuariomodif() {
        return this.idusuariomodif;
    }
    
    public void setIdusuariomodif(Integer idusuariomodif) {
        this.idusuariomodif = idusuariomodif;
    }
    public Date getFechacreac() {
        return this.fechacreac;
    }
    
    public void setFechacreac(Date fechacreac) {
        this.fechacreac = fechacreac;
    }
    public Date getFechamodif() {
        return this.fechamodif;
    }
    
    public void setFechamodif(Date fechamodif) {
        this.fechamodif = fechamodif;
    }
    public Integer getCantidaddaniado() {
        return this.cantidaddaniado;
    }
    
    public void setCantidaddaniado(Integer cantidaddaniado) {
        this.cantidaddaniado = cantidaddaniado;
    }
    public Integer getIdcobservacion() {
        return this.idcobservacion;
    }
    
    public void setIdcobservacion(Integer idcobservacion) {
        this.idcobservacion = idcobservacion;
    }
    public Double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Double subtotal) {
        this.subtotal = subtotal;
    }
    public Double getPreciocompraunid() {
        return this.preciocompraunid;
    }
    
    public void setPreciocompraunid(Double preciocompraunid) {
        this.preciocompraunid = preciocompraunid;
    }




}


