package SIGEV.BE;
// Generated 30/05/2015 06:26:47 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TDevolucionProducto generated by hbm2java
 */
public class TDevolucionProducto  implements java.io.Serializable {


     private int iddevolucionproducto;
     private TProducto TProducto;
     private Date fechadevolucion;
     private String estado;
     private String observacion;
     private Integer idusuariocreac;
     private Integer idusuariomodif;
     private Date fechacreac;
     private Date fechamodif;
     private Integer cantidadproducto;
     private Date fecharetorno;
     private Integer idcestadoproceso;

    public TDevolucionProducto() {
    }

	
    public TDevolucionProducto(int iddevolucionproducto) {
        this.iddevolucionproducto = iddevolucionproducto;
    }
    public TDevolucionProducto(int iddevolucionproducto, TProducto TProducto, Date fechadevolucion, String estado, String observacion, Integer idusuariocreac, Integer idusuariomodif, Date fechacreac, Date fechamodif, Integer cantidadproducto, Date fecharetorno, Integer idcestadoproceso) {
       this.iddevolucionproducto = iddevolucionproducto;
       this.TProducto = TProducto;
       this.fechadevolucion = fechadevolucion;
       this.estado = estado;
       this.observacion = observacion;
       this.idusuariocreac = idusuariocreac;
       this.idusuariomodif = idusuariomodif;
       this.fechacreac = fechacreac;
       this.fechamodif = fechamodif;
       this.cantidadproducto = cantidadproducto;
       this.fecharetorno = fecharetorno;
       this.idcestadoproceso = idcestadoproceso;
    }
   
    public int getIddevolucionproducto() {
        return this.iddevolucionproducto;
    }
    
    public void setIddevolucionproducto(int iddevolucionproducto) {
        this.iddevolucionproducto = iddevolucionproducto;
    }
    public TProducto getTProducto() {
        return this.TProducto;
    }
    
    public void setTProducto(TProducto TProducto) {
        this.TProducto = TProducto;
    }
    public Date getFechadevolucion() {
        return this.fechadevolucion;
    }
    
    public void setFechadevolucion(Date fechadevolucion) {
        this.fechadevolucion = fechadevolucion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Integer getIdusuariocreac() {
        return this.idusuariocreac;
    }
    
    public void setIdusuariocreac(Integer idusuariocreac) {
        this.idusuariocreac = idusuariocreac;
    }
    public Integer getIdusuariomodif() {
        return this.idusuariomodif;
    }
    
    public void setIdusuariomodif(Integer idusuariomodif) {
        this.idusuariomodif = idusuariomodif;
    }
    public Date getFechacreac() {
        return this.fechacreac;
    }
    
    public void setFechacreac(Date fechacreac) {
        this.fechacreac = fechacreac;
    }
    public Date getFechamodif() {
        return this.fechamodif;
    }
    
    public void setFechamodif(Date fechamodif) {
        this.fechamodif = fechamodif;
    }
    public Integer getCantidadproducto() {
        return this.cantidadproducto;
    }
    
    public void setCantidadproducto(Integer cantidadproducto) {
        this.cantidadproducto = cantidadproducto;
    }
    public Date getFecharetorno() {
        return this.fecharetorno;
    }
    
    public void setFecharetorno(Date fecharetorno) {
        this.fecharetorno = fecharetorno;
    }
    public Integer getIdcestadoproceso() {
        return this.idcestadoproceso;
    }
    
    public void setIdcestadoproceso(Integer idcestadoproceso) {
        this.idcestadoproceso = idcestadoproceso;
    }




}


