package SIGEV.BE;
// Generated 30/05/2015 06:26:47 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TFrecuencia generated by hbm2java
 */
public class TFrecuencia  implements java.io.Serializable {


     private int idfechapedido;
     private TVenta TVenta;
     private Date fechapedido;
     private String estado;
     private String observacion;
     private Integer idusuariocreac;
     private Integer idusuariomodif;
     private Date fechacreac;
     private Date fechamodif;

    public TFrecuencia() {
    }

	
    public TFrecuencia(int idfechapedido) {
        this.idfechapedido = idfechapedido;
    }
    public TFrecuencia(int idfechapedido, TVenta TVenta, Date fechapedido, String estado, String observacion, Integer idusuariocreac, Integer idusuariomodif, Date fechacreac, Date fechamodif) {
       this.idfechapedido = idfechapedido;
       this.TVenta = TVenta;
       this.fechapedido = fechapedido;
       this.estado = estado;
       this.observacion = observacion;
       this.idusuariocreac = idusuariocreac;
       this.idusuariomodif = idusuariomodif;
       this.fechacreac = fechacreac;
       this.fechamodif = fechamodif;
    }
   
    public int getIdfechapedido() {
        return this.idfechapedido;
    }
    
    public void setIdfechapedido(int idfechapedido) {
        this.idfechapedido = idfechapedido;
    }
    public TVenta getTVenta() {
        return this.TVenta;
    }
    
    public void setTVenta(TVenta TVenta) {
        this.TVenta = TVenta;
    }
    public Date getFechapedido() {
        return this.fechapedido;
    }
    
    public void setFechapedido(Date fechapedido) {
        this.fechapedido = fechapedido;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Integer getIdusuariocreac() {
        return this.idusuariocreac;
    }
    
    public void setIdusuariocreac(Integer idusuariocreac) {
        this.idusuariocreac = idusuariocreac;
    }
    public Integer getIdusuariomodif() {
        return this.idusuariomodif;
    }
    
    public void setIdusuariomodif(Integer idusuariomodif) {
        this.idusuariomodif = idusuariomodif;
    }
    public Date getFechacreac() {
        return this.fechacreac;
    }
    
    public void setFechacreac(Date fechacreac) {
        this.fechacreac = fechacreac;
    }
    public Date getFechamodif() {
        return this.fechamodif;
    }
    
    public void setFechamodif(Date fechamodif) {
        this.fechamodif = fechamodif;
    }




}


