package SIGEV.BE;
// Generated 30/05/2015 06:26:47 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * THistorialAsistencia generated by hbm2java
 */
public class THistorialAsistencia  implements java.io.Serializable {


     private int idhistorialasistencia;
     private TPersonal TPersonal;
     private String estado;
     private String observacion;
     private Integer idusuariocreac;
     private Integer idusuariomodif;
     private Date fechacreac;
     private Date fechamodif;

    public THistorialAsistencia() {
    }

	
    public THistorialAsistencia(int idhistorialasistencia) {
        this.idhistorialasistencia = idhistorialasistencia;
    }
    public THistorialAsistencia(int idhistorialasistencia, TPersonal TPersonal, String estado, String observacion, Integer idusuariocreac, Integer idusuariomodif, Date fechacreac, Date fechamodif) {
       this.idhistorialasistencia = idhistorialasistencia;
       this.TPersonal = TPersonal;
       this.estado = estado;
       this.observacion = observacion;
       this.idusuariocreac = idusuariocreac;
       this.idusuariomodif = idusuariomodif;
       this.fechacreac = fechacreac;
       this.fechamodif = fechamodif;
    }
   
    public int getIdhistorialasistencia() {
        return this.idhistorialasistencia;
    }
    
    public void setIdhistorialasistencia(int idhistorialasistencia) {
        this.idhistorialasistencia = idhistorialasistencia;
    }
    public TPersonal getTPersonal() {
        return this.TPersonal;
    }
    
    public void setTPersonal(TPersonal TPersonal) {
        this.TPersonal = TPersonal;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Integer getIdusuariocreac() {
        return this.idusuariocreac;
    }
    
    public void setIdusuariocreac(Integer idusuariocreac) {
        this.idusuariocreac = idusuariocreac;
    }
    public Integer getIdusuariomodif() {
        return this.idusuariomodif;
    }
    
    public void setIdusuariomodif(Integer idusuariomodif) {
        this.idusuariomodif = idusuariomodif;
    }
    public Date getFechacreac() {
        return this.fechacreac;
    }
    
    public void setFechacreac(Date fechacreac) {
        this.fechacreac = fechacreac;
    }
    public Date getFechamodif() {
        return this.fechamodif;
    }
    
    public void setFechamodif(Date fechamodif) {
        this.fechamodif = fechamodif;
    }




}


