package SIGEV.BE;
// Generated 30/05/2015 06:26:47 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TPago generated by hbm2java
 */
public class TPago  implements java.io.Serializable {


     private int idpago;
     private TPersonal TPersonal;
     private Date fechainicio;
     private Date fechafin;
     private Double monto;
     private String estado;
     private String observacion;
     private Integer idusuariocreac;
     private Integer idusuariomodif;
     private Date fechacreac;
     private Date fechamodif;
     private Integer minutostardanza;
     private Integer horasextra;
     private Double aumento;
     private Double descuento;
     private Double montototal;

    public TPago() {
    }

	
    public TPago(int idpago) {
        this.idpago = idpago;
    }
    public TPago(int idpago, TPersonal TPersonal, Date fechainicio, Date fechafin, Double monto, String estado, String observacion, Integer idusuariocreac, Integer idusuariomodif, Date fechacreac, Date fechamodif, Integer minutostardanza, Integer horasextra, Double aumento, Double descuento, Double montototal) {
       this.idpago = idpago;
       this.TPersonal = TPersonal;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.monto = monto;
       this.estado = estado;
       this.observacion = observacion;
       this.idusuariocreac = idusuariocreac;
       this.idusuariomodif = idusuariomodif;
       this.fechacreac = fechacreac;
       this.fechamodif = fechamodif;
       this.minutostardanza = minutostardanza;
       this.horasextra = horasextra;
       this.aumento = aumento;
       this.descuento = descuento;
       this.montototal = montototal;
    }
   
    public int getIdpago() {
        return this.idpago;
    }
    
    public void setIdpago(int idpago) {
        this.idpago = idpago;
    }
    public TPersonal getTPersonal() {
        return this.TPersonal;
    }
    
    public void setTPersonal(TPersonal TPersonal) {
        this.TPersonal = TPersonal;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Integer getIdusuariocreac() {
        return this.idusuariocreac;
    }
    
    public void setIdusuariocreac(Integer idusuariocreac) {
        this.idusuariocreac = idusuariocreac;
    }
    public Integer getIdusuariomodif() {
        return this.idusuariomodif;
    }
    
    public void setIdusuariomodif(Integer idusuariomodif) {
        this.idusuariomodif = idusuariomodif;
    }
    public Date getFechacreac() {
        return this.fechacreac;
    }
    
    public void setFechacreac(Date fechacreac) {
        this.fechacreac = fechacreac;
    }
    public Date getFechamodif() {
        return this.fechamodif;
    }
    
    public void setFechamodif(Date fechamodif) {
        this.fechamodif = fechamodif;
    }
    public Integer getMinutostardanza() {
        return this.minutostardanza;
    }
    
    public void setMinutostardanza(Integer minutostardanza) {
        this.minutostardanza = minutostardanza;
    }
    public Integer getHorasextra() {
        return this.horasextra;
    }
    
    public void setHorasextra(Integer horasextra) {
        this.horasextra = horasextra;
    }
    public Double getAumento() {
        return this.aumento;
    }
    
    public void setAumento(Double aumento) {
        this.aumento = aumento;
    }
    public Double getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Double descuento) {
        this.descuento = descuento;
    }
    public Double getMontototal() {
        return this.montototal;
    }
    
    public void setMontototal(Double montototal) {
        this.montototal = montototal;
    }




}


