package SIGEV.BE;
// Generated 30/05/2015 06:26:47 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TPersonal generated by hbm2java
 */
public class TPersonal  implements java.io.Serializable {


     private int idpersonal;
     private TPersona TPersona;
     private Integer idcrutaasignada;
     private Integer idctipopersonal;
     private String estado;
     private String observacion;
     private Integer idusuariocreac;
     private Integer idusuariomodif;
     private Date fechacreac;
     private Date fechamodif;
     private Integer idcestadopersonal;
     private Integer idcmodalidadpago;
     private Date horaentrada;
     private Date horasalida;
     private String urlfoto;
     private String urlimagen;
     private Double montopago;
     private Date fechaingreso;
     private Set TPagos = new HashSet(0);
     private Set THistorialAsistencias = new HashSet(0);

    public TPersonal() {
    }

	
    public TPersonal(int idpersonal) {
        this.idpersonal = idpersonal;
    }
    public TPersonal(int idpersonal, TPersona TPersona, Integer idcrutaasignada, Integer idctipopersonal, String estado, String observacion, Integer idusuariocreac, Integer idusuariomodif, Date fechacreac, Date fechamodif, Integer idcestadopersonal, Integer idcmodalidadpago, Date horaentrada, Date horasalida, String urlfoto, String urlimagen, Double montopago, Date fechaingreso, Set TPagos, Set THistorialAsistencias) {
       this.idpersonal = idpersonal;
       this.TPersona = TPersona;
       this.idcrutaasignada = idcrutaasignada;
       this.idctipopersonal = idctipopersonal;
       this.estado = estado;
       this.observacion = observacion;
       this.idusuariocreac = idusuariocreac;
       this.idusuariomodif = idusuariomodif;
       this.fechacreac = fechacreac;
       this.fechamodif = fechamodif;
       this.idcestadopersonal = idcestadopersonal;
       this.idcmodalidadpago = idcmodalidadpago;
       this.horaentrada = horaentrada;
       this.horasalida = horasalida;
       this.urlfoto = urlfoto;
       this.urlimagen = urlimagen;
       this.montopago = montopago;
       this.fechaingreso = fechaingreso;
       this.TPagos = TPagos;
       this.THistorialAsistencias = THistorialAsistencias;
    }
   
    public int getIdpersonal() {
        return this.idpersonal;
    }
    
    public void setIdpersonal(int idpersonal) {
        this.idpersonal = idpersonal;
    }
    public TPersona getTPersona() {
        return this.TPersona;
    }
    
    public void setTPersona(TPersona TPersona) {
        this.TPersona = TPersona;
    }
    public Integer getIdcrutaasignada() {
        return this.idcrutaasignada;
    }
    
    public void setIdcrutaasignada(Integer idcrutaasignada) {
        this.idcrutaasignada = idcrutaasignada;
    }
    public Integer getIdctipopersonal() {
        return this.idctipopersonal;
    }
    
    public void setIdctipopersonal(Integer idctipopersonal) {
        this.idctipopersonal = idctipopersonal;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Integer getIdusuariocreac() {
        return this.idusuariocreac;
    }
    
    public void setIdusuariocreac(Integer idusuariocreac) {
        this.idusuariocreac = idusuariocreac;
    }
    public Integer getIdusuariomodif() {
        return this.idusuariomodif;
    }
    
    public void setIdusuariomodif(Integer idusuariomodif) {
        this.idusuariomodif = idusuariomodif;
    }
    public Date getFechacreac() {
        return this.fechacreac;
    }
    
    public void setFechacreac(Date fechacreac) {
        this.fechacreac = fechacreac;
    }
    public Date getFechamodif() {
        return this.fechamodif;
    }
    
    public void setFechamodif(Date fechamodif) {
        this.fechamodif = fechamodif;
    }
    public Integer getIdcestadopersonal() {
        return this.idcestadopersonal;
    }
    
    public void setIdcestadopersonal(Integer idcestadopersonal) {
        this.idcestadopersonal = idcestadopersonal;
    }
    public Integer getIdcmodalidadpago() {
        return this.idcmodalidadpago;
    }
    
    public void setIdcmodalidadpago(Integer idcmodalidadpago) {
        this.idcmodalidadpago = idcmodalidadpago;
    }
    public Date getHoraentrada() {
        return this.horaentrada;
    }
    
    public void setHoraentrada(Date horaentrada) {
        this.horaentrada = horaentrada;
    }
    public Date getHorasalida() {
        return this.horasalida;
    }
    
    public void setHorasalida(Date horasalida) {
        this.horasalida = horasalida;
    }
    public String getUrlfoto() {
        return this.urlfoto;
    }
    
    public void setUrlfoto(String urlfoto) {
        this.urlfoto = urlfoto;
    }
    public String getUrlimagen() {
        return this.urlimagen;
    }
    
    public void setUrlimagen(String urlimagen) {
        this.urlimagen = urlimagen;
    }
    public Double getMontopago() {
        return this.montopago;
    }
    
    public void setMontopago(Double montopago) {
        this.montopago = montopago;
    }
    public Date getFechaingreso() {
        return this.fechaingreso;
    }
    
    public void setFechaingreso(Date fechaingreso) {
        this.fechaingreso = fechaingreso;
    }
    public Set getTPagos() {
        return this.TPagos;
    }
    
    public void setTPagos(Set TPagos) {
        this.TPagos = TPagos;
    }
    public Set getTHistorialAsistencias() {
        return this.THistorialAsistencias;
    }
    
    public void setTHistorialAsistencias(Set THistorialAsistencias) {
        this.THistorialAsistencias = THistorialAsistencias;
    }




}


