package SIGEV.BE;
// Generated 30/05/2015 06:26:47 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TPrivilegio generated by hbm2java
 */
public class TPrivilegio  implements java.io.Serializable {


     private int idprivilegio;
     private String denominacion;
     private Integer idmenu;
     private Integer orden;
     private Integer idusuariocreac;
     private Integer idusuariomodif;
     private String estado;
     private String observacion;
     private Date fechacreac;
     private Date fechamodif;
     private String idprivilegioboton;
     private String imagen;
     private Set TRolPrivilegios = new HashSet(0);

    public TPrivilegio() {
    }

	
    public TPrivilegio(int idprivilegio) {
        this.idprivilegio = idprivilegio;
    }
    public TPrivilegio(int idprivilegio, String denominacion, Integer idmenu, Integer orden, Integer idusuariocreac, Integer idusuariomodif, String estado, String observacion, Date fechacreac, Date fechamodif, String idprivilegioboton, String imagen, Set TRolPrivilegios) {
       this.idprivilegio = idprivilegio;
       this.denominacion = denominacion;
       this.idmenu = idmenu;
       this.orden = orden;
       this.idusuariocreac = idusuariocreac;
       this.idusuariomodif = idusuariomodif;
       this.estado = estado;
       this.observacion = observacion;
       this.fechacreac = fechacreac;
       this.fechamodif = fechamodif;
       this.idprivilegioboton = idprivilegioboton;
       this.imagen = imagen;
       this.TRolPrivilegios = TRolPrivilegios;
    }
   
    public int getIdprivilegio() {
        return this.idprivilegio;
    }
    
    public void setIdprivilegio(int idprivilegio) {
        this.idprivilegio = idprivilegio;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public Integer getIdmenu() {
        return this.idmenu;
    }
    
    public void setIdmenu(Integer idmenu) {
        this.idmenu = idmenu;
    }
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }
    public Integer getIdusuariocreac() {
        return this.idusuariocreac;
    }
    
    public void setIdusuariocreac(Integer idusuariocreac) {
        this.idusuariocreac = idusuariocreac;
    }
    public Integer getIdusuariomodif() {
        return this.idusuariomodif;
    }
    
    public void setIdusuariomodif(Integer idusuariomodif) {
        this.idusuariomodif = idusuariomodif;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechacreac() {
        return this.fechacreac;
    }
    
    public void setFechacreac(Date fechacreac) {
        this.fechacreac = fechacreac;
    }
    public Date getFechamodif() {
        return this.fechamodif;
    }
    
    public void setFechamodif(Date fechamodif) {
        this.fechamodif = fechamodif;
    }
    public String getIdprivilegioboton() {
        return this.idprivilegioboton;
    }
    
    public void setIdprivilegioboton(String idprivilegioboton) {
        this.idprivilegioboton = idprivilegioboton;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Set getTRolPrivilegios() {
        return this.TRolPrivilegios;
    }
    
    public void setTRolPrivilegios(Set TRolPrivilegios) {
        this.TRolPrivilegios = TRolPrivilegios;
    }




}


