package SIGEV.BE;
// Generated 30/05/2015 06:26:47 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TProveedor generated by hbm2java
 */
public class TProveedor  implements java.io.Serializable {


     private int idproveedor;
     private TPersona TPersona;
     private Integer idctipoproveedor;
     private String estado;
     private String observacion;
     private Integer idusuariocreac;
     private Integer idusuariomodif;
     private Date fechacreac;
     private Date fechamodif;
     private Set TCompras = new HashSet(0);

    public TProveedor() {
    }

	
    public TProveedor(int idproveedor) {
        this.idproveedor = idproveedor;
    }
    public TProveedor(int idproveedor, TPersona TPersona, Integer idctipoproveedor, String estado, String observacion, Integer idusuariocreac, Integer idusuariomodif, Date fechacreac, Date fechamodif, Set TCompras) {
       this.idproveedor = idproveedor;
       this.TPersona = TPersona;
       this.idctipoproveedor = idctipoproveedor;
       this.estado = estado;
       this.observacion = observacion;
       this.idusuariocreac = idusuariocreac;
       this.idusuariomodif = idusuariomodif;
       this.fechacreac = fechacreac;
       this.fechamodif = fechamodif;
       this.TCompras = TCompras;
    }
   
    public int getIdproveedor() {
        return this.idproveedor;
    }
    
    public void setIdproveedor(int idproveedor) {
        this.idproveedor = idproveedor;
    }
    public TPersona getTPersona() {
        return this.TPersona;
    }
    
    public void setTPersona(TPersona TPersona) {
        this.TPersona = TPersona;
    }
    public Integer getIdctipoproveedor() {
        return this.idctipoproveedor;
    }
    
    public void setIdctipoproveedor(Integer idctipoproveedor) {
        this.idctipoproveedor = idctipoproveedor;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Integer getIdusuariocreac() {
        return this.idusuariocreac;
    }
    
    public void setIdusuariocreac(Integer idusuariocreac) {
        this.idusuariocreac = idusuariocreac;
    }
    public Integer getIdusuariomodif() {
        return this.idusuariomodif;
    }
    
    public void setIdusuariomodif(Integer idusuariomodif) {
        this.idusuariomodif = idusuariomodif;
    }
    public Date getFechacreac() {
        return this.fechacreac;
    }
    
    public void setFechacreac(Date fechacreac) {
        this.fechacreac = fechacreac;
    }
    public Date getFechamodif() {
        return this.fechamodif;
    }
    
    public void setFechamodif(Date fechamodif) {
        this.fechamodif = fechamodif;
    }
    public Set getTCompras() {
        return this.TCompras;
    }
    
    public void setTCompras(Set TCompras) {
        this.TCompras = TCompras;
    }




}


