package SIGEV.BE;
// Generated 30/05/2015 06:26:47 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TRol generated by hbm2java
 */
public class TRol  implements java.io.Serializable {


     private int idrol;
     private String nombrerol;
     private String descripcion;
     private Integer idusuariocreac;
     private Integer idusuariomodif;
     private String estado;
     private String observacion;
     private Date fechacreac;
     private Date fachamodif;
     private Set TUsuarios = new HashSet(0);
     private Set TRolPrivilegios = new HashSet(0);
     private Set TMenuRols = new HashSet(0);

    public TRol() {
    }

	
    public TRol(int idrol) {
        this.idrol = idrol;
    }
    public TRol(int idrol, String nombrerol, String descripcion, Integer idusuariocreac, Integer idusuariomodif, String estado, String observacion, Date fechacreac, Date fachamodif, Set TUsuarios, Set TRolPrivilegios, Set TMenuRols) {
       this.idrol = idrol;
       this.nombrerol = nombrerol;
       this.descripcion = descripcion;
       this.idusuariocreac = idusuariocreac;
       this.idusuariomodif = idusuariomodif;
       this.estado = estado;
       this.observacion = observacion;
       this.fechacreac = fechacreac;
       this.fachamodif = fachamodif;
       this.TUsuarios = TUsuarios;
       this.TRolPrivilegios = TRolPrivilegios;
       this.TMenuRols = TMenuRols;
    }
   
    public int getIdrol() {
        return this.idrol;
    }
    
    public void setIdrol(int idrol) {
        this.idrol = idrol;
    }
    public String getNombrerol() {
        return this.nombrerol;
    }
    
    public void setNombrerol(String nombrerol) {
        this.nombrerol = nombrerol;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getIdusuariocreac() {
        return this.idusuariocreac;
    }
    
    public void setIdusuariocreac(Integer idusuariocreac) {
        this.idusuariocreac = idusuariocreac;
    }
    public Integer getIdusuariomodif() {
        return this.idusuariomodif;
    }
    
    public void setIdusuariomodif(Integer idusuariomodif) {
        this.idusuariomodif = idusuariomodif;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechacreac() {
        return this.fechacreac;
    }
    
    public void setFechacreac(Date fechacreac) {
        this.fechacreac = fechacreac;
    }
    public Date getFachamodif() {
        return this.fachamodif;
    }
    
    public void setFachamodif(Date fachamodif) {
        this.fachamodif = fachamodif;
    }
    public Set getTUsuarios() {
        return this.TUsuarios;
    }
    
    public void setTUsuarios(Set TUsuarios) {
        this.TUsuarios = TUsuarios;
    }
    public Set getTRolPrivilegios() {
        return this.TRolPrivilegios;
    }
    
    public void setTRolPrivilegios(Set TRolPrivilegios) {
        this.TRolPrivilegios = TRolPrivilegios;
    }
    public Set getTMenuRols() {
        return this.TMenuRols;
    }
    
    public void setTMenuRols(Set TMenuRols) {
        this.TMenuRols = TMenuRols;
    }




}


