package SIGEV.BE;
// Generated 30/05/2015 06:26:47 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TRolPrivilegio generated by hbm2java
 */
public class TRolPrivilegio  implements java.io.Serializable {


     private int idmenurol;
     private TPrivilegio TPrivilegio;
     private TRol TRol;
     private String estado;
     private String observacion;
     private Integer idusuariocreac;
     private Integer idusuariomodif;
     private Date fechacreac;
     private Date fechamodif;

    public TRolPrivilegio() {
    }

	
    public TRolPrivilegio(int idmenurol) {
        this.idmenurol = idmenurol;
    }
    public TRolPrivilegio(int idmenurol, TPrivilegio TPrivilegio, TRol TRol, String estado, String observacion, Integer idusuariocreac, Integer idusuariomodif, Date fechacreac, Date fechamodif) {
       this.idmenurol = idmenurol;
       this.TPrivilegio = TPrivilegio;
       this.TRol = TRol;
       this.estado = estado;
       this.observacion = observacion;
       this.idusuariocreac = idusuariocreac;
       this.idusuariomodif = idusuariomodif;
       this.fechacreac = fechacreac;
       this.fechamodif = fechamodif;
    }
   
    public int getIdmenurol() {
        return this.idmenurol;
    }
    
    public void setIdmenurol(int idmenurol) {
        this.idmenurol = idmenurol;
    }
    public TPrivilegio getTPrivilegio() {
        return this.TPrivilegio;
    }
    
    public void setTPrivilegio(TPrivilegio TPrivilegio) {
        this.TPrivilegio = TPrivilegio;
    }
    public TRol getTRol() {
        return this.TRol;
    }
    
    public void setTRol(TRol TRol) {
        this.TRol = TRol;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Integer getIdusuariocreac() {
        return this.idusuariocreac;
    }
    
    public void setIdusuariocreac(Integer idusuariocreac) {
        this.idusuariocreac = idusuariocreac;
    }
    public Integer getIdusuariomodif() {
        return this.idusuariomodif;
    }
    
    public void setIdusuariomodif(Integer idusuariomodif) {
        this.idusuariomodif = idusuariomodif;
    }
    public Date getFechacreac() {
        return this.fechacreac;
    }
    
    public void setFechacreac(Date fechacreac) {
        this.fechacreac = fechacreac;
    }
    public Date getFechamodif() {
        return this.fechamodif;
    }
    
    public void setFechamodif(Date fechamodif) {
        this.fechamodif = fechamodif;
    }




}


